[font]
size = 18.0

[cursor]
style = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[colors.cursor]
background = "#5ec4ff"
text = "#f8f8f2"

[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/theme.toml"
]

[[keyboard.bindings]]
action = "ToggleViMode"
mods = "Control"
key = "Space"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "A"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"


[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
