creation_rules:
  - path_regex: _secrets\.yaml$
    key_groups:
      - age:
        - age1c6xvu75xanvh0zgllqz9zrqv9g6ctf4pysngdlgcu27mf2q23d7s0rphn7
        - age1cgqkldjp38n7e5shv5ptakrrzmjn0pcr7juld7kjdwqfpmqn59wq2s4hlu
        - age10nctks2e0tkzc7asv0z49fhtdulcq5yrzuf0p7xpxty5v6lxwvusltgjpy
