// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1760744479);
user_pref("app.update.lastUpdateTime.background-update-timer", 1760744479);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1760744479);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1760109020);
user_pref("browser.laterrun.bookkeeping.sessionCount", 25);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240801134912");
user_pref("browser.startup.homepage_override.mstone", "115.14.0");
user_pref("browser.theme.toolbar-theme", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20250709174312");
user_pref("extensions.lastAppVersion", "7.0.20");
user_pref("extensions.lastPlatformVersion", "115.14.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"better-bibtex@iris-advies.com\":\"23868552-dfb2-430d-b7c3-d7e6b9697a6f\",\"Knowledge4Zotero@windingwind.com\":\"d2240810-68f0-4faa-a73c-7ff7fb5e4265\"}");
user_pref("extensions.zotero.Knowledge4Zotero.latestTourVersion", 1);
user_pref("extensions.zotero.Knowledge4Zotero.persist.workspaceContext", "{\"pinnedPane\":\"\"}");
user_pref("extensions.zotero.Knowledge4Zotero.persist.workspaceOutline", "{\"outlineType\":1}");
user_pref("extensions.zotero.Knowledge4Zotero.syncNoteIds", "[\"\"]");
user_pref("extensions.zotero.Knowledge4Zotero.template.[ExportLatexFileContent]", "\"${{\\n  return latexContent;\\n}}$\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[ExportMDFileContent]", "\"${{\\n  return mdContent;\\n}}$\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[ExportMDFileHeaderV2]", "\"${{\\n  let header = {};\\n  header.tags = noteItem.getTags().map((_t) => _t.tag);\\n  header.parent = noteItem.parentItem\\n    ? noteItem.parentItem.getField(\\\"title\\\")\\n    : \\\"\\\";\\n  header.collections = (\\n    await Zotero.Collections.getCollectionsContainingItems([\\n      (noteItem.parentItem || noteItem).id,\\n    ])\\n  ).map((c) => c.name);\\n  return JSON.stringify(header);\\n}}$\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[ExportMDFileNameV2]", "\"${(noteItem.getNoteTitle ? noteItem.getNoteTitle().replace(/[/\\\\\\\\?%*:|\\\"<> ]/g, \\\"-\\\") + \\\"-\\\" : \\\"\\\")}${noteItem.key}.md\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[QuickImportV2]", "\"<blockquote>\\n${{\\n  return await Zotero.BetterNotes.api.convert.link2html(link, {noteItem, dryRun: _env.dryRun});\\n}}$\\n</blockquote>\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[QuickInsertV3]", "\"// @use-markdown\\n[${linkText}](${link})\"");
user_pref("extensions.zotero.Knowledge4Zotero.template.[QuickNoteV5]", "\"${{\\n  let res = \\\"\\\";\\n  if (annotationItem.annotationComment) {\\n    res += await Zotero.BetterNotes.api.convert.md2html(\\n      annotationItem.annotationComment\\n    );\\n  }\\n  res += await Zotero.BetterNotes.api.convert.annotations2html([annotationItem], {noteItem, ignoreComment: true});\\n  return res;\\n}}$\"");
user_pref("extensions.zotero.Knowledge4Zotero.templateKeys", "[\"[QuickInsertV3]\",\"[QuickImportV2]\",\"[QuickNoteV5]\",\"[ExportMDFileNameV2]\",\"[ExportMDFileHeaderV2]\",\"[ExportMDFileContent]\",\"[ExportLatexFileContent]\"]");
user_pref("extensions.zotero.autoRenameFiles.fileTypes", "application/pdf,application/epub+zip,image/,audio/,video/");
user_pref("extensions.zotero.baseAttachmentPath", "/home/xin/Grimoire/PDF");
user_pref("extensions.zotero.dataDir", "/home/xin/Grimoire/.Zotero");
user_pref("extensions.zotero.export.lastNoteTranslator", "897a81c2-9f60-4bec-ae6b-85a5030b8be5");
user_pref("extensions.zotero.export.lastTranslator", "f895aa0d-f28e-47fe-b247-2ea77c6ed583");
user_pref("extensions.zotero.export.noteQuickCopy.setting", "{\"mode\":\"export\",\"id\":\"897a81c2-9f60-4bec-ae6b-85a5030b8be5\",\"options\":{\"includeAppLinks\":true}}");
user_pref("extensions.zotero.export.noteTranslatorSettings", "{\"includeAppLinks\":true}");
user_pref("extensions.zotero.export.quickCopy.setting", "export=9cb70025-a888-4a29-a210-93ec52da40d4");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":true,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"biblatexAPA\":false,\"biblatexChicago\":false,\"keepUpdated\":true,\"worker\":true,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidanceShown.quickFormat", true);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-cite");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.newItemTypeMRU", "book");
user_pref("extensions.zotero.openReaderInNewWindow", true);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.Knowledge4Zotero-windingwind-com-bn-note-inbound-link.open", true);
user_pref("extensions.zotero.panes.Knowledge4Zotero-windingwind-com-bn-note-outbound-link.open", true);
user_pref("extensions.zotero.panes.Knowledge4Zotero-windingwind-com-bn-note-relation.open", true);
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.saveRelativeAttachmentPath", true);
user_pref("extensions.zotero.sync.reminder.setUp.enabled", false);
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1760112960);
user_pref("extensions.zotero.translators.better-bibtex.autoExport.%2Fhome%2Fxin%2FGrimoire%2FOverview%2FMy%20Library%2ebib", "{\"path\":\"/home/xin/Grimoire/Overview/My Library.bib\",\"translatorID\":\"f895aa0d-f28e-47fe-b247-2ea77c6ed583\",\"type\":\"library\",\"id\":1,\"status\":\"done\",\"error\":\"\",\"recursive\":false,\"updated\":1760753052551,\"enabled\":true,\"asciiBibLaTeX\":false,\"biblatexExtendedNameFormat\":true,\"DOIandURL\":\"both\",\"exportNotes\":true,\"useJournalAbbreviation\":false,\"biblatexAPA\":false,\"biblatexChicago\":false,\"created\":1760744482359}");
user_pref("extensions.zotero.translators.better-bibtex.autoExport.%2Fhome%2Fxin%2FGrimoire%2FOverview%2Fzotero%2ebib", "{\"path\":\"/home/xin/Grimoire/Overview/zotero.bib\",\"translatorID\":\"f895aa0d-f28e-47fe-b247-2ea77c6ed583\",\"type\":\"library\",\"id\":1,\"status\":\"done\",\"error\":\"\",\"recursive\":false,\"updated\":1760753052562,\"enabled\":true,\"asciiBibLaTeX\":false,\"biblatexExtendedNameFormat\":true,\"DOIandURL\":\"both\",\"exportNotes\":true,\"useJournalAbbreviation\":false,\"biblatexAPA\":false,\"biblatexChicago\":false,\"created\":1760744482360}");
user_pref("extensions.zotero.translators.better-bibtex.baseAttachmentPath", "/home/xin/Grimoire/PDF");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + shorttitle(3, 3) + year");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3, 3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/home/xin/.nix-profile/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.1.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1760744639);
user_pref("intl.accept_languages", "en-US, en");
user_pref("layout.css.nesting.enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1760744639587");
user_pref("security.sandbox.content.tempDirSuffix", "4035415e-63f4-45b3-b0b6-c0bd9dc15d71");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1760109239);
